

Epoch 0: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 104/104 [00:02<00:00, 51.49it/s, loss=3.07, lr=2.08e-6, step=104]Traceback (most recent call last):
  File "/home/sehwan/MIIL/CA-layout-generation/dlt/main.py", line 104, in <module>
    app.run(main)
  File "/home/sehwan/anaconda3/envs/CAL/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/sehwan/anaconda3/envs/CAL/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/sehwan/MIIL/CA-layout-generation/dlt/main.py", line 76, in main
    TrainLoopCAL(accelerator=accelerator, model=model, diffusion=noise_scheduler,
  File "/home/sehwan/MIIL/CA-layout-generation/dlt/trainers/cal_trainer.py", line 222, in train
    self.CAL_train_epsilon(epoch)
  File "/home/sehwan/MIIL/CA-layout-generation/dlt/trainers/cal_trainer.py", line 584, in CAL_train_epsilon
    "image_features": val_noisy_image_features['image_features'] * val_batch["padding_mask"]}
IndexError: too many indices for tensor of dimension 3